# Generated by Django 4.0.4 on 2022-05-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('gender', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('birth', models.DateField(null=True)),
            ],
        ),
    ]
